#!/bin/sh
# https://docs.fedoraproject.org/en-US/quick-docs/setup_rpmfusion/
pm_install()
{
	assert_root

	case "${pm_distro}" in
		"fedora")
			;;
		*)
			printf '%s\n' "unsupported os" # $(rpm -E %fedora) doesn't work
			exit 1
			;;
	esac
	
	dnf install -y \
		https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
		https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
}