#!/bin/sh
# https://docs.fedoraproject.org/en-US/quick-docs/setup_rpmfusion/
pm_package_name="rpmfusion"
pm_install()
{
	case "${pm_distro}" in
		"fedora")
			;;
		*)
			printf '%s\n' "unsupported os" # $(rpm -E %fedora) doesn't work
			exit 1
			;;
	esac

	if [ $(id -u) != 0 ]; then
		printf '%s\n' "package requires root"
		exit 1
	fi
	
	sudo dnf install -y \
		https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm &
	
	sudo dnf install -y \
		https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm &

	wait
}